//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LLMDesktopAssistant.Localization.Resources {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Locale {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Locale() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LLMDesktopAssistant.Localization.Resources.Locale", typeof(Locale).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ask agent.
        /// </summary>
        public static string agent_ask_question {
            get {
                return ResourceManager.GetString("agent-ask_question", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Call agent.
        /// </summary>
        public static string agent_call {
            get {
                return ResourceManager.GetString("agent-call", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Agents.
        /// </summary>
        public static string agents {
            get {
                return ResourceManager.GetString("agents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ask.
        /// </summary>
        public static string ask_for_confirmation {
            get {
                return ResourceManager.GetString("ask_for_confirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Whether to ask before executing tool.
        /// </summary>
        public static string ask_for_confirmation_tooltip {
            get {
                return ResourceManager.GetString("ask_for_confirmation_tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Browser.
        /// </summary>
        public static string browser {
            get {
                return ResourceManager.GetString("browser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Browser: Execute script.
        /// </summary>
        public static string browser_execute_javascript {
            get {
                return ResourceManager.GetString("browser-execute_javascript", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Browser: Get markup.
        /// </summary>
        public static string browser_get_html {
            get {
                return ResourceManager.GetString("browser-get_html", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Browser: Navigate to URI.
        /// </summary>
        public static string browser_navigate_to_uri {
            get {
                return ResourceManager.GetString("browser-navigate_to_uri", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Calculate.
        /// </summary>
        public static string calculate {
            get {
                return ResourceManager.GetString("calculate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Calculation.
        /// </summary>
        public static string calculation {
            get {
                return ResourceManager.GetString("calculation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Cancel.
        /// </summary>
        public static string cancel {
            get {
                return ResourceManager.GetString("cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Chat.
        /// </summary>
        public static string chat {
            get {
                return ResourceManager.GetString("chat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Attach file....
        /// </summary>
        public static string chat_attach_file_hint {
            get {
                return ResourceManager.GetString("chat-attach_file_hint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Enable MCP.
        /// </summary>
        public static string chat_enable_mcp {
            get {
                return ResourceManager.GetString("chat-enable_mcp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Enable tools.
        /// </summary>
        public static string chat_enable_tools {
            get {
                return ResourceManager.GetString("chat-enable_tools", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Enter your message....
        /// </summary>
        public static string chat_input_hint {
            get {
                return ResourceManager.GetString("chat-input_hint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Chat model.
        /// </summary>
        public static string chat_model_hint {
            get {
                return ResourceManager.GetString("chat_model_hint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Send message.
        /// </summary>
        public static string chat_send_button_hint {
            get {
                return ResourceManager.GetString("chat-send_button_hint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на General.
        /// </summary>
        public static string chat_settings_general {
            get {
                return ResourceManager.GetString("chat_settings_general", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Settings.
        /// </summary>
        public static string chat_settings_hint {
            get {
                return ResourceManager.GetString("chat-settings_hint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на MCP.
        /// </summary>
        public static string chat_settings_mcp {
            get {
                return ResourceManager.GetString("chat_settings_mcp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Tools.
        /// </summary>
        public static string chat_settings_tools {
            get {
                return ResourceManager.GetString("chat_settings_tools", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Chats.
        /// </summary>
        public static string chats {
            get {
                return ResourceManager.GetString("chats", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Connect.
        /// </summary>
        public static string connect {
            get {
                return ResourceManager.GetString("connect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Copy to clipboard.
        /// </summary>
        public static string copy {
            get {
                return ResourceManager.GetString("copy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Disconnect.
        /// </summary>
        public static string disconnect {
            get {
                return ResourceManager.GetString("disconnect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Empty.
        /// </summary>
        public static string empty_model {
            get {
                return ResourceManager.GetString("empty_model", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Enable.
        /// </summary>
        public static string enable {
            get {
                return ResourceManager.GetString("enable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Error: {0}.
        /// </summary>
        public static string error_model {
            get {
                return ResourceManager.GetString("error_model", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Execute Bash script.
        /// </summary>
        public static string execute_bash {
            get {
                return ResourceManager.GetString("execute-bash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Execute Lua script.
        /// </summary>
        public static string execute_lua {
            get {
                return ResourceManager.GetString("execute-lua", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Execute Powershell script.
        /// </summary>
        public static string execute_powershell {
            get {
                return ResourceManager.GetString("execute-powershell", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Execute Python script.
        /// </summary>
        public static string execute_python {
            get {
                return ResourceManager.GetString("execute-python", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Execute Shell script in Python virt. environment.
        /// </summary>
        public static string execute_python_venv_shell {
            get {
                return ResourceManager.GetString("execute-python_venv_shell", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Execute Shell script.
        /// </summary>
        public static string execute_shell {
            get {
                return ResourceManager.GetString("execute-shell", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на File system.
        /// </summary>
        public static string filesystem {
            get {
                return ResourceManager.GetString("filesystem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Delete file.
        /// </summary>
        public static string fs_delete_file {
            get {
                return ResourceManager.GetString("fs-delete_file", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на List files in directory.
        /// </summary>
        public static string fs_list_directory {
            get {
                return ResourceManager.GetString("fs-list_directory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Read file.
        /// </summary>
        public static string fs_read_file {
            get {
                return ResourceManager.GetString("fs-read_file", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Write file.
        /// </summary>
        public static string fs_write_file {
            get {
                return ResourceManager.GetString("fs-write_file", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на General.
        /// </summary>
        public static string general {
            get {
                return ResourceManager.GetString("general", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Print.
        /// </summary>
        public static string general_print {
            get {
                return ResourceManager.GetString("general-print", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Generate GUID.
        /// </summary>
        public static string generate_GUID {
            get {
                return ResourceManager.GetString("generate_GUID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Generate random decimal number.
        /// </summary>
        public static string generate_random_float {
            get {
                return ResourceManager.GetString("generate_random_float", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Generate random integer.
        /// </summary>
        public static string generate_random_integer {
            get {
                return ResourceManager.GetString("generate_random_integer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Input.
        /// </summary>
        public static string input {
            get {
                return ResourceManager.GetString("input", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Enter text.
        /// </summary>
        public static string input_enter_text {
            get {
                return ResourceManager.GetString("input-enter_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Move mouse.
        /// </summary>
        public static string input_move_mouse {
            get {
                return ResourceManager.GetString("input-move_mouse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Move mouse.
        /// </summary>
        public static string input_move_mouse_delta {
            get {
                return ResourceManager.GetString("input-move_mouse_delta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Press key.
        /// </summary>
        public static string input_press_key {
            get {
                return ResourceManager.GetString("input-press_key", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Connection type.
        /// </summary>
        public static string mcp_connection_type {
            get {
                return ResourceManager.GetString("mcp-connection_type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Endpoint.
        /// </summary>
        public static string mcp_endpoint {
            get {
                return ResourceManager.GetString("mcp-endpoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Name.
        /// </summary>
        public static string name {
            get {
                return ResourceManager.GetString("name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на New chat.
        /// </summary>
        public static string new_chat {
            get {
                return ResourceManager.GetString("new_chat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ok.
        /// </summary>
        public static string ok {
            get {
                return ResourceManager.GetString("ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Personality.
        /// </summary>
        public static string personality_hint {
            get {
                return ResourceManager.GetString("personality_hint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Get Python installed packages.
        /// </summary>
        public static string python_get_installed_packages_list {
            get {
                return ResourceManager.GetString("python-get_installed_packages_list", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Reasoning process.
        /// </summary>
        public static string reasoning {
            get {
                return ResourceManager.GetString("reasoning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Regenerate.
        /// </summary>
        public static string regenerate {
            get {
                return ResourceManager.GetString("regenerate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Resend.
        /// </summary>
        public static string resend {
            get {
                return ResourceManager.GetString("resend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Reset.
        /// </summary>
        public static string reset {
            get {
                return ResourceManager.GetString("reset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Sample.
        /// </summary>
        public static string sample {
            get {
                return ResourceManager.GetString("sample", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Scripting.
        /// </summary>
        public static string scripting {
            get {
                return ResourceManager.GetString("scripting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Select model.
        /// </summary>
        public static string select_model {
            get {
                return ResourceManager.GetString("select_model", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Select working directory.
        /// </summary>
        public static string select_working_directory {
            get {
                return ResourceManager.GetString("select_working_directory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Settings.
        /// </summary>
        public static string settings {
            get {
                return ResourceManager.GetString("settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Default.
        /// </summary>
        public static string settings_default_id {
            get {
                return ResourceManager.GetString("settings_default_id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Profile:.
        /// </summary>
        public static string settings_profile {
            get {
                return ResourceManager.GetString("settings_profile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Summarizer model.
        /// </summary>
        public static string summarizer_model_hint {
            get {
                return ResourceManager.GetString("summarizer_model_hint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на System instructions.
        /// </summary>
        public static string system_instructions_hint {
            get {
                return ResourceManager.GetString("system_instructions_hint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Niggalink AI.
        /// </summary>
        public static string title {
            get {
                return ResourceManager.GetString("title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Tool arguments:.
        /// </summary>
        public static string tool_arguments {
            get {
                return ResourceManager.GetString("tool-arguments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на {0} tools.
        /// </summary>
        public static string tool_name_suffix_hint {
            get {
                return ResourceManager.GetString("tool_name_suffix_hint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Tool result:.
        /// </summary>
        public static string tool_result {
            get {
                return ResourceManager.GetString("tool-result", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Tools.
        /// </summary>
        public static string tools_hint {
            get {
                return ResourceManager.GetString("tools_hint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Voice chat.
        /// </summary>
        public static string voice_chat {
            get {
                return ResourceManager.GetString("voice_chat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Web.
        /// </summary>
        public static string web {
            get {
                return ResourceManager.GetString("web", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Download.
        /// </summary>
        public static string web_download {
            get {
                return ResourceManager.GetString("web-download", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на GET request.
        /// </summary>
        public static string web_get {
            get {
                return ResourceManager.GetString("web-get", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Fetch HTML.
        /// </summary>
        public static string web_get_html {
            get {
                return ResourceManager.GetString("web-get_html", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Web parse.
        /// </summary>
        public static string web_parse {
            get {
                return ResourceManager.GetString("web-parse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на POST request.
        /// </summary>
        public static string web_post {
            get {
                return ResourceManager.GetString("web-post", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Web request.
        /// </summary>
        public static string web_request {
            get {
                return ResourceManager.GetString("web-request", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Web search.
        /// </summary>
        public static string web_search {
            get {
                return ResourceManager.GetString("web-search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Check web status.
        /// </summary>
        public static string web_status {
            get {
                return ResourceManager.GetString("web-status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Working directory.
        /// </summary>
        public static string working_directory_hint {
            get {
                return ResourceManager.GetString("working_directory_hint", resourceCulture);
            }
        }
    }
}
