//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LLMDesktopAssistant.Localization.Resources {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Locale {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Locale() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LLMDesktopAssistant.Localization.Resources.Locale", typeof(Locale).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ask agent.
        /// </summary>
        public static string agent_ask_question {
            get {
                return ResourceManager.GetString("agent-ask_question", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Call agent.
        /// </summary>
        public static string agent_call {
            get {
                return ResourceManager.GetString("agent-call", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Browser.
        /// </summary>
        public static string browser {
            get {
                return ResourceManager.GetString("browser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Browser: Execute script.
        /// </summary>
        public static string browser_execute_javascript {
            get {
                return ResourceManager.GetString("browser-execute_javascript", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Browser: Get markup.
        /// </summary>
        public static string browser_get_html {
            get {
                return ResourceManager.GetString("browser-get_html", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Browser: Navigate to URI.
        /// </summary>
        public static string browser_navigate_to_uri {
            get {
                return ResourceManager.GetString("browser-navigate_to_uri", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Calculate.
        /// </summary>
        public static string calculation_calculate {
            get {
                return ResourceManager.GetString("calculation-calculate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Chat.
        /// </summary>
        public static string chat {
            get {
                return ResourceManager.GetString("chat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Attach file....
        /// </summary>
        public static string chat_attach_file_hint {
            get {
                return ResourceManager.GetString("chat-attach_file_hint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Enter your message....
        /// </summary>
        public static string chat_input_hint {
            get {
                return ResourceManager.GetString("chat-input_hint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Send message.
        /// </summary>
        public static string chat_send_button_hint {
            get {
                return ResourceManager.GetString("chat-send_button_hint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Settings.
        /// </summary>
        public static string chat_settings_hint {
            get {
                return ResourceManager.GetString("chat-settings_hint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Execute Lua script.
        /// </summary>
        public static string execute_lua {
            get {
                return ResourceManager.GetString("execute-lua", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Execute Python script.
        /// </summary>
        public static string execute_python {
            get {
                return ResourceManager.GetString("execute-python", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Execute Shell script in Python virt. environment.
        /// </summary>
        public static string execute_python_venv_shell {
            get {
                return ResourceManager.GetString("execute-python_venv_shell", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Execute Shell script.
        /// </summary>
        public static string execute_shell {
            get {
                return ResourceManager.GetString("execute-shell", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Copy to clipboard.
        /// </summary>
        public static string general_copy {
            get {
                return ResourceManager.GetString("general-copy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Generate GUID.
        /// </summary>
        public static string general_generateGUID {
            get {
                return ResourceManager.GetString("general-generateGUID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Generate random decimal number.
        /// </summary>
        public static string general_GenerateRandomFloat {
            get {
                return ResourceManager.GetString("general-GenerateRandomFloat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Generate random integer.
        /// </summary>
        public static string general_generateRandomInteger {
            get {
                return ResourceManager.GetString("general-generateRandomInteger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Print.
        /// </summary>
        public static string general_print {
            get {
                return ResourceManager.GetString("general-print", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Enter text.
        /// </summary>
        public static string input_enter_text {
            get {
                return ResourceManager.GetString("input-enter_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Move mouse.
        /// </summary>
        public static string input_move_mouse {
            get {
                return ResourceManager.GetString("input-move_mouse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Move mouse.
        /// </summary>
        public static string input_move_mouse_delta {
            get {
                return ResourceManager.GetString("input-move_mouse_delta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Press key.
        /// </summary>
        public static string input_press_key {
            get {
                return ResourceManager.GetString("input-press_key", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Sample.
        /// </summary>
        public static string sample {
            get {
                return ResourceManager.GetString("sample", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на RomeCore&apos;s desktop temple.
        /// </summary>
        public static string title {
            get {
                return ResourceManager.GetString("title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Tool arguments:.
        /// </summary>
        public static string tool_arguments {
            get {
                return ResourceManager.GetString("tool-arguments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Tool result:.
        /// </summary>
        public static string tool_result {
            get {
                return ResourceManager.GetString("tool-result", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Voice chat.
        /// </summary>
        public static string voice_chat {
            get {
                return ResourceManager.GetString("voice_chat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Download.
        /// </summary>
        public static string web_download {
            get {
                return ResourceManager.GetString("web-download", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на GET request.
        /// </summary>
        public static string web_get {
            get {
                return ResourceManager.GetString("web-get", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Fetch HTML.
        /// </summary>
        public static string web_get_html {
            get {
                return ResourceManager.GetString("web-get_html", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Web parse.
        /// </summary>
        public static string web_parse {
            get {
                return ResourceManager.GetString("web-parse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на POST request.
        /// </summary>
        public static string web_post {
            get {
                return ResourceManager.GetString("web-post", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Web request.
        /// </summary>
        public static string web_request {
            get {
                return ResourceManager.GetString("web-request", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Web search.
        /// </summary>
        public static string web_search {
            get {
                return ResourceManager.GetString("web-search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Check web status.
        /// </summary>
        public static string web_status {
            get {
                return ResourceManager.GetString("web-status", resourceCulture);
            }
        }
    }
}
