namespace LLMDesktopAssistant.Agents.Tasks
{
	/// <summary>
	/// Usage statistics for an agent task.
	/// </summary>
	public class AgentUsageStatistics
	{
		/// <summary>
		/// The number of input tokens processed by the agent task.
		/// </summary>
		public required int InputTokens { get; init; }

		/// <summary>
		/// The number of output tokens generated by the agent task.
		/// </summary>
		public required int OutputTokens { get; init; }

		/// <summary>
		/// The number of input tokens that were served from the provider cache.
		/// </summary>
		public required int InputCacheHitTokens { get; init; }

		/// <summary>
		/// The number of input tokens that were not served from the provider cache.
		/// </summary>
		public required int InputCacheMissTokens { get; init; }

		/// <summary>
		/// The time taken to generate the first token.
		/// </summary>
		public required TimeSpan TimeToFirstToken { get; init; }

		/// <summary>
		/// The time taken to generate all tokens.
		/// </summary>
		public required TimeSpan InferenceTime { get; init; }

		/// <summary>
		/// The total time taken to execute the task, including response generation and tool invocation.
		/// </summary>
		public required TimeSpan ExecutionTime { get; init; }
	}
}
