using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using LLMDesktopAssistant.Core.Services;
using MoonSharp.Interpreter;

namespace LLMDesktopAssistant.Core.Scripting
{
	[Service]
	public class LuaService
	{
		private readonly Script _lua;

		/// <summary>
		/// Gets the Lua interpreter instance.
		/// </summary>
		public Script Lua => _lua;

		public LuaService()
		{
			_lua = new Script(CoreModules.Preset_SoftSandbox);
		}

		/// <summary>
		/// Executes the provided Lua code.
		/// </summary>
		/// <param name="lua">The Lua code to execute.</param>
		/// <returns>The result of the Lua execution.</returns>
		public DynValue Execute(string lua)
		{
			return _lua.DoString(lua);
		}

		/// <summary>
		/// Executes the provided Lua code and captures any output generated by print statements.
		/// </summary>
		/// <param name="lua">The Lua code to execute.</param>
		/// <param name="printOutput">The list to capture output into.</param>
		/// <returns>The result of the Lua execution.</returns>
		public DynValue Execute(string lua, out List<string> printOutput)
		{
			var _printOutput = new List<string>();
			printOutput = _printOutput;

			var prevPrint = _lua.Options.DebugPrint;
			try
			{
				_lua.Options.DebugPrint = str => _printOutput.Add(str);
				return _lua.DoString(lua);
			}
			finally
			{
				_lua.Options.DebugPrint = prevPrint;
			}
		}
	}
}