using System.Collections.Immutable;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Diagnostics;
using Microsoft.CodeAnalysis.Operations;

namespace LLMDesktopAssistant.SourceGenerators
{
	/// <summary>
	/// Reports direct accesses to inherited settings properties that bypass inheritance
	/// resolution. A property is considered inherited when its declaring type provides
	/// a <c>GetEffective&lt;Name&gt;</c> accessor (generated by
	/// <see cref="InheritedSettingsGenerator"/>); such properties must be read through
	/// <c>GetEffective&lt;Name&gt;()</c> and written through <c>SetEffective&lt;Name&gt;(...)</c>.
	/// References inside the declaring type itself are allowed and not reported.
	/// </summary>
	[DiagnosticAnalyzer(LanguageNames.CSharp)]
	public sealed class DirectSettingsAccessAnalyzer : DiagnosticAnalyzer
	{
		/// <summary>
		/// The diagnostic ID reported for direct accesses to inherited settings properties.
		/// </summary>
		public const string DiagnosticId = "DASSW001";

		private static readonly DiagnosticDescriptor Rule = new(
			DiagnosticId,
			"Direct access to inherited settings property",
			"Direct access to '{0}' bypasses inheritance resolution; use '{1}' instead",
			"LLMDesktopAssistant",
			DiagnosticSeverity.Warning,
			isEnabledByDefault: true,
			description: "Access the property through the generated GetEffective/SetEffective accessor to respect the configured inheritance level.");

		/// <inheritdoc/>
		public override ImmutableArray<DiagnosticDescriptor> SupportedDiagnostics => [Rule];

		/// <inheritdoc/>
		public override void Initialize(AnalysisContext context)
		{
			context.ConfigureGeneratedCodeAnalysis(GeneratedCodeAnalysisFlags.None);
			context.EnableConcurrentExecution();
			context.RegisterOperationAction(AnalyzePropertyReference, OperationKind.PropertyReference);
		}

		private static void AnalyzePropertyReference(OperationAnalysisContext context)
		{
			var reference = (IPropertyReferenceOperation)context.Operation;
			var property = reference.Property;
			var declaringType = property.ContainingType;
			if (property.IsStatic || declaringType is null)
				return;

			// Only properties that have a generated GetEffective<Name> accessor take part
			// in inheritance resolution.
			if (!HasEffectiveAccessor(declaringType, property.Name))
				return;

			// References inside the declaring type itself are the source of truth
			// (e.g. the generated GetEffective/SetEffective implementations).
			if (IsInsideType(context.ContainingSymbol, declaringType))
				return;

			var isWrite = reference.Parent is IAssignmentOperation { Target: var target } && target == reference
				|| reference.Parent is ICompoundAssignmentOperation;

			var replacement = isWrite
				? $"SetEffective{property.Name}(...)"
				: $"GetEffective{property.Name}()";

			context.ReportDiagnostic(Diagnostic.Create(Rule, reference.Syntax.GetLocation(), property.Name, replacement));
		}

		private static bool HasEffectiveAccessor(INamedTypeSymbol type, string propertyName)
		{
			foreach (var member in type.GetMembers("GetEffective" + propertyName))
			{
				if (member is IMethodSymbol)
					return true;
			}
			return false;
		}

		private static bool IsInsideType(ISymbol? symbol, INamedTypeSymbol type)
		{
			for (var current = symbol; current is not null; current = current.ContainingSymbol)
			{
				if (SymbolEqualityComparer.Default.Equals(current, type))
					return true;
			}
			return false;
		}
	}
}
