using System.Collections.Immutable;
using LLMDesktopAssistant.SourceGenerators;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.Diagnostics;

namespace LLMDesktopAssistant.Tests;

public class DirectSettingsAccessAnalyzerTests
{
	private static readonly MetadataReference[] _references = ((string)AppContext.GetData("TRUSTED_PLATFORM_ASSEMBLIES")!)
		.Split(Path.PathSeparator)
		.Select(p => MetadataReference.CreateFromFile(p))
		.ToArray();

	private const string SampleSource = """
		namespace TestNamespace
		{
			public class Settings
			{
				public string Value { get; set; } = string.Empty;

				// Simulates the accessor generated by InheritedSettingsGenerator.
				public string GetEffectiveValue() => Value;
				public string ReadInside() => Value; // allowed inside the declaring type
			}

			public class Consumer
			{
				public string Read(Settings s) => s.Value; // DASSW001

				public string ReadEffective(Settings s) => s.GetEffectiveValue();

				public void Write(Settings s) => s.Value = "x"; // DASSW001

				public string NameOfRead(Settings s) => nameof(s.Value); // compile-time name -> ok

				public string Plain(PlainSettings s) => s.Value; // no accessor -> ok
			}

			public class PlainSettings
			{
				public string Value { get; set; } = string.Empty;
			}
		}
		""";

	private static ImmutableArray<Diagnostic> RunAnalyzer(string source)
	{
		var compilation = CSharpCompilation.Create(
			"AnalyzerTests",
			[CSharpSyntaxTree.ParseText(source)],
			_references,
			new CSharpCompilationOptions(OutputKind.DynamicallyLinkedLibrary));

		var withAnalyzers = compilation.WithAnalyzers(
			ImmutableArray.Create<DiagnosticAnalyzer>(new DirectSettingsAccessAnalyzer()));
		return withAnalyzers.GetAnalyzerDiagnosticsAsync().GetAwaiter().GetResult();
	}

	[Fact]
	public void ReportsWarning_ForDirectAccessOutsideDeclaringType()
	{
		var diagnostics = RunAnalyzer(SampleSource)
			.Where(d => d.Id == DirectSettingsAccessAnalyzer.DiagnosticId)
			.ToList();

		var expectedLines = SampleSource.Split('\n')
			.Select((line, i) => (line, lineNumber: i + 1))
			.Where(x => x.line.Contains("// DASSW001"))
			.Select(x => x.lineNumber)
			.ToArray();

		var actualLines = diagnostics
			.Select(d => d.Location.GetLineSpan().StartLinePosition.Line + 1)
			.Order()
			.ToArray();

		Assert.Equal(expectedLines, actualLines);
		Assert.All(diagnostics, d => Assert.Equal(DiagnosticSeverity.Warning, d.Severity));
	}
	
	[Fact]
	public void Message_SuggestsEffectiveAccessor()
	{
		var diagnostics = RunAnalyzer(SampleSource)
			.Where(d => d.Id == DirectSettingsAccessAnalyzer.DiagnosticId)
			.ToList();

		// Read access -> GetEffective accessor
		Assert.Contains(diagnostics, d => d.GetMessage().Contains("GetEffectiveValue()"));

		// Write access -> SetEffective accessor
		Assert.Contains(diagnostics, d => d.GetMessage().Contains("SetEffectiveValue(...)"));
	}

	[Fact]
	public void NoDiagnostics_WhenOnlyEffectiveAccessorsAreUsed()
	{
		const string source = """
			namespace TestNamespace
			{
				public class Settings
				{
					public string Value { get; set; } = string.Empty;

					public string GetEffectiveValue() => Value;

					public string ReadInside() => Value;
				}

				public class Consumer
				{
					public string Read(Settings s) => s.GetEffectiveValue();
				}
			}
			""";

		var diagnostics = RunAnalyzer(source)
			.Where(d => d.Id == DirectSettingsAccessAnalyzer.DiagnosticId);

		Assert.Empty(diagnostics);
	}

	[Fact]
	public void NoDiagnostics_ForNameOfReferences()
	{
		const string source = """
			namespace TestNamespace
			{
				public class Settings
				{
					public string Value { get; set; } = string.Empty;

					public string GetEffectiveValue() => Value;
				}

				public class Consumer
				{
					public string NameOfRead(Settings s) => nameof(s.Value);
					public string NameOfTypeRead(Settings s) => nameof(Settings.Value);
					public void NameOfWrite(Settings s) { var _ = nameof(s.Value); }
				}
			}
			""";

		var diagnostics = RunAnalyzer(source)
			.Where(d => d.Id == DirectSettingsAccessAnalyzer.DiagnosticId);

		Assert.Empty(diagnostics);
	}

	[Fact]
	public void NoDiagnostics_ForPropertiesWithoutEffectiveAccessor()
	{
		const string source = """
			namespace TestNamespace
			{
				public class Settings
				{
					public string Value { get; set; } = string.Empty;
				}

				public class Consumer
				{
					public string Read(Settings s) => s.Value;
				}
			}
			""";

		var diagnostics = RunAnalyzer(source)
			.Where(d => d.Id == DirectSettingsAccessAnalyzer.DiagnosticId);

		Assert.Empty(diagnostics);
	}
}
