//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LLMDesktopAssistant.Core.Localization.Resources {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Locale {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Locale() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LLMDesktopAssistant.Core.Localization.Resources.Locale", typeof(Locale).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Add.
        /// </summary>
        public static string add {
            get {
                return ResourceManager.GetString("add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ask agent.
        /// </summary>
        public static string agent_ask_question {
            get {
                return ResourceManager.GetString("agent-ask_question", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Call agent.
        /// </summary>
        public static string agent_call {
            get {
                return ResourceManager.GetString("agent-call", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Agents.
        /// </summary>
        public static string agents {
            get {
                return ResourceManager.GetString("agents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Applicate.
        /// </summary>
        public static string application_applicate_hint {
            get {
                return ResourceManager.GetString("application-applicate_hint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Semantic description.
        /// </summary>
        public static string application_description {
            get {
                return ResourceManager.GetString("application-description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на End byte.
        /// </summary>
        public static string application_end_byte {
            get {
                return ResourceManager.GetString("application-end_byte", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на End line.
        /// </summary>
        public static string application_end_line {
            get {
                return ResourceManager.GetString("application-end_line", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Full contents.
        /// </summary>
        public static string application_full_contents {
            get {
                return ResourceManager.GetString("application-full_contents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Full hexadecimal dump.
        /// </summary>
        public static string application_full_hexadecimal {
            get {
                return ResourceManager.GetString("application-full_hexadecimal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Partial hexadecimal dump.
        /// </summary>
        public static string application_hexadecimal_partial {
            get {
                return ResourceManager.GetString("application-hexadecimal_partial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Application mode.
        /// </summary>
        public static string application_mode_hint {
            get {
                return ResourceManager.GetString("application-mode_hint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Only reference.
        /// </summary>
        public static string application_only_reference {
            get {
                return ResourceManager.GetString("application-only_reference", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Partial contents.
        /// </summary>
        public static string application_partial_contents {
            get {
                return ResourceManager.GetString("application-partial_contents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Start byte.
        /// </summary>
        public static string application_start_byte {
            get {
                return ResourceManager.GetString("application-start_byte", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Start line.
        /// </summary>
        public static string application_start_line {
            get {
                return ResourceManager.GetString("application-start_line", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ask.
        /// </summary>
        public static string ask_for_confirmation {
            get {
                return ResourceManager.GetString("ask_for_confirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Whether to ask before executing tool.
        /// </summary>
        public static string ask_for_confirmation_tooltip {
            get {
                return ResourceManager.GetString("ask_for_confirmation_tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Add URL.
        /// </summary>
        public static string attachment_add_url_hint {
            get {
                return ResourceManager.GetString("attachment-add_url_hint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Attach files.
        /// </summary>
        public static string attachment_attach_files_hint {
            get {
                return ResourceManager.GetString("attachment-attach_files_hint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Drop files here.
        /// </summary>
        public static string attachment_drop_files_here {
            get {
                return ResourceManager.GetString("attachment-drop_files_here", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Attachment URL.
        /// </summary>
        public static string attachment_url_hint {
            get {
                return ResourceManager.GetString("attachment-url_hint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Browser.
        /// </summary>
        public static string browser {
            get {
                return ResourceManager.GetString("browser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Browser: Execute script.
        /// </summary>
        public static string browser_execute_javascript {
            get {
                return ResourceManager.GetString("browser-execute_javascript", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Browser: Get markup.
        /// </summary>
        public static string browser_get_html {
            get {
                return ResourceManager.GetString("browser-get_html", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Browser: Navigate to URI.
        /// </summary>
        public static string browser_navigate_to_uri {
            get {
                return ResourceManager.GetString("browser-navigate_to_uri", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Calculate.
        /// </summary>
        public static string calculate {
            get {
                return ResourceManager.GetString("calculate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Calculation.
        /// </summary>
        public static string calculation {
            get {
                return ResourceManager.GetString("calculation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Cancel.
        /// </summary>
        public static string cancel {
            get {
                return ResourceManager.GetString("cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Chat.
        /// </summary>
        public static string chat {
            get {
                return ResourceManager.GetString("chat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Attach file....
        /// </summary>
        public static string chat_attach_file_hint {
            get {
                return ResourceManager.GetString("chat-attach_file_hint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Enable MCP.
        /// </summary>
        public static string chat_enable_mcp {
            get {
                return ResourceManager.GetString("chat-enable_mcp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Enable tools.
        /// </summary>
        public static string chat_enable_tools {
            get {
                return ResourceManager.GetString("chat-enable_tools", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Enter your message....
        /// </summary>
        public static string chat_input_hint {
            get {
                return ResourceManager.GetString("chat-input_hint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Send message.
        /// </summary>
        public static string chat_send_button_hint {
            get {
                return ResourceManager.GetString("chat-send_button_hint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на General.
        /// </summary>
        public static string chat_settings_general {
            get {
                return ResourceManager.GetString("chat_settings_general", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Settings.
        /// </summary>
        public static string chat_settings_hint {
            get {
                return ResourceManager.GetString("chat-settings_hint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на MCP.
        /// </summary>
        public static string chat_settings_mcp {
            get {
                return ResourceManager.GetString("chat_settings_mcp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Prompts.
        /// </summary>
        public static string chat_settings_prompts {
            get {
                return ResourceManager.GetString("chat_settings_prompts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Tools.
        /// </summary>
        public static string chat_settings_tools {
            get {
                return ResourceManager.GetString("chat_settings_tools", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Chats.
        /// </summary>
        public static string chats {
            get {
                return ResourceManager.GetString("chats", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Connect.
        /// </summary>
        public static string connect {
            get {
                return ResourceManager.GetString("connect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Copy to clipboard.
        /// </summary>
        public static string copy {
            get {
                return ResourceManager.GetString("copy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Disconnect.
        /// </summary>
        public static string disconnect {
            get {
                return ResourceManager.GetString("disconnect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Empty.
        /// </summary>
        public static string empty_model {
            get {
                return ResourceManager.GetString("empty_model", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Enable.
        /// </summary>
        public static string enable {
            get {
                return ResourceManager.GetString("enable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Error: {0}.
        /// </summary>
        public static string error_model {
            get {
                return ResourceManager.GetString("error_model", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Execute Bash script.
        /// </summary>
        public static string execute_bash {
            get {
                return ResourceManager.GetString("execute-bash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Execute Lua script.
        /// </summary>
        public static string execute_lua {
            get {
                return ResourceManager.GetString("execute-lua", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Execute Powershell script.
        /// </summary>
        public static string execute_powershell {
            get {
                return ResourceManager.GetString("execute-powershell", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Execute Python script.
        /// </summary>
        public static string execute_python {
            get {
                return ResourceManager.GetString("execute-python", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Execute Shell script in Python virt. environment.
        /// </summary>
        public static string execute_python_venv_shell {
            get {
                return ResourceManager.GetString("execute-python_venv_shell", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Execute Shell script.
        /// </summary>
        public static string execute_shell {
            get {
                return ResourceManager.GetString("execute-shell", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на File system.
        /// </summary>
        public static string filesystem {
            get {
                return ResourceManager.GetString("filesystem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Apply patch to file.
        /// </summary>
        public static string fs_apply_diff {
            get {
                return ResourceManager.GetString("fs-apply_diff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Copy file.
        /// </summary>
        public static string fs_copy_file {
            get {
                return ResourceManager.GetString("fs-copy_file", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Delete file.
        /// </summary>
        public static string fs_delete_file {
            get {
                return ResourceManager.GetString("fs-delete_file", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Get file info.
        /// </summary>
        public static string fs_get_file_info {
            get {
                return ResourceManager.GetString("fs-get_file_info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Filesystem grep search.
        /// </summary>
        public static string fs_grep {
            get {
                return ResourceManager.GetString("fs-grep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на List files in directory.
        /// </summary>
        public static string fs_list_directory {
            get {
                return ResourceManager.GetString("fs-list_directory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Open file.
        /// </summary>
        public static string fs_open_file {
            get {
                return ResourceManager.GetString("fs-open_file", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Read binary file.
        /// </summary>
        public static string fs_read_binary_file {
            get {
                return ResourceManager.GetString("fs-read_binary_file", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Read document.
        /// </summary>
        public static string fs_read_document_file {
            get {
                return ResourceManager.GetString("fs-read_document_file", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Read file.
        /// </summary>
        public static string fs_read_file {
            get {
                return ResourceManager.GetString("fs-read_file", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Rename file.
        /// </summary>
        public static string fs_rename_file {
            get {
                return ResourceManager.GetString("fs-rename_file", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Replace text in file.
        /// </summary>
        public static string fs_replace {
            get {
                return ResourceManager.GetString("fs-replace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Write binary file.
        /// </summary>
        public static string fs_write_binary_file {
            get {
                return ResourceManager.GetString("fs-write_binary_file", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Write file.
        /// </summary>
        public static string fs_write_file {
            get {
                return ResourceManager.GetString("fs-write_file", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на General.
        /// </summary>
        public static string general {
            get {
                return ResourceManager.GetString("general", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Print.
        /// </summary>
        public static string general_print {
            get {
                return ResourceManager.GetString("general-print", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Generate GUID.
        /// </summary>
        public static string generate_GUID {
            get {
                return ResourceManager.GetString("generate_GUID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Generate random decimal number.
        /// </summary>
        public static string generate_random_float {
            get {
                return ResourceManager.GetString("generate_random_float", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Generate random integer.
        /// </summary>
        public static string generate_random_integer {
            get {
                return ResourceManager.GetString("generate_random_integer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Input.
        /// </summary>
        public static string input {
            get {
                return ResourceManager.GetString("input", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Enter text.
        /// </summary>
        public static string input_enter_text {
            get {
                return ResourceManager.GetString("input-enter_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Move mouse.
        /// </summary>
        public static string input_move_mouse {
            get {
                return ResourceManager.GetString("input-move_mouse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Move mouse.
        /// </summary>
        public static string input_move_mouse_delta {
            get {
                return ResourceManager.GetString("input-move_mouse_delta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Press key.
        /// </summary>
        public static string input_press_key {
            get {
                return ResourceManager.GetString("input-press_key", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Connection type.
        /// </summary>
        public static string mcp_connection_type {
            get {
                return ResourceManager.GetString("mcp-connection_type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Endpoint.
        /// </summary>
        public static string mcp_endpoint {
            get {
                return ResourceManager.GetString("mcp-endpoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на MCP manager.
        /// </summary>
        public static string mcp_manager_header {
            get {
                return ResourceManager.GetString("mcp_manager_header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на MCP manager.
        /// </summary>
        public static string mcp_manager_hint {
            get {
                return ResourceManager.GetString("mcp_manager_hint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Meta-tools.
        /// </summary>
        public static string metatools {
            get {
                return ResourceManager.GetString("metatools", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Create or update meta-tool.
        /// </summary>
        public static string metatools_create_or_update {
            get {
                return ResourceManager.GetString("metatools-create_or_update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Delete meta-tool.
        /// </summary>
        public static string metatools_delete {
            get {
                return ResourceManager.GetString("metatools-delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Get information about meta-tool.
        /// </summary>
        public static string metatools_get_info {
            get {
                return ResourceManager.GetString("metatools-get_info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на List meta-tools.
        /// </summary>
        public static string metatools_list {
            get {
                return ResourceManager.GetString("metatools-list", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Rename meta-tool.
        /// </summary>
        public static string metatools_rename {
            get {
                return ResourceManager.GetString("metatools-rename", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Name.
        /// </summary>
        public static string name {
            get {
                return ResourceManager.GetString("name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на New chat.
        /// </summary>
        public static string new_chat {
            get {
                return ResourceManager.GetString("new_chat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ok.
        /// </summary>
        public static string ok {
            get {
                return ResourceManager.GetString("ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Niggalink AI.
        /// </summary>
        public static string persona_niggalink_ai {
            get {
                return ResourceManager.GetString("persona-niggalink_ai", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Personality.
        /// </summary>
        public static string personality_hint {
            get {
                return ResourceManager.GetString("personality_hint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Category.
        /// </summary>
        public static string prompt_category {
            get {
                return ResourceManager.GetString("prompt_category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Uncategorized.
        /// </summary>
        public static string prompt_category_uncategorized {
            get {
                return ResourceManager.GetString("prompt_category_uncategorized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Additional components.
        /// </summary>
        public static string prompt_components {
            get {
                return ResourceManager.GetString("prompt_components", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Enter custom persona....
        /// </summary>
        public static string prompt_custom_persona_hint {
            get {
                return ResourceManager.GetString("prompt_custom_persona_hint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Edit Component.
        /// </summary>
        public static string prompt_edit_component {
            get {
                return ResourceManager.GetString("prompt_edit_component", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Edit Persona.
        /// </summary>
        public static string prompt_edit_persona {
            get {
                return ResourceManager.GetString("prompt_edit_persona", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Import.
        /// </summary>
        public static string prompt_import {
            get {
                return ResourceManager.GetString("prompt_import", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Import component.
        /// </summary>
        public static string prompt_import_component {
            get {
                return ResourceManager.GetString("prompt_import_component", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Import persona.
        /// </summary>
        public static string prompt_import_persona {
            get {
                return ResourceManager.GetString("prompt_import_persona", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Prompt manager.
        /// </summary>
        public static string prompt_manager_header {
            get {
                return ResourceManager.GetString("prompt_manager_header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Prompt manager.
        /// </summary>
        public static string prompt_manager_hint {
            get {
                return ResourceManager.GetString("prompt_manager_hint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Name.
        /// </summary>
        public static string prompt_name {
            get {
                return ResourceManager.GetString("prompt_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на New component.
        /// </summary>
        public static string prompt_new_component {
            get {
                return ResourceManager.GetString("prompt_new_component", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на New persona.
        /// </summary>
        public static string prompt_new_persona {
            get {
                return ResourceManager.GetString("prompt_new_persona", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Persona.
        /// </summary>
        public static string prompt_persona {
            get {
                return ResourceManager.GetString("prompt_persona", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Personas.
        /// </summary>
        public static string prompt_personas {
            get {
                return ResourceManager.GetString("prompt_personas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Select persona....
        /// </summary>
        public static string prompt_select_persona {
            get {
                return ResourceManager.GetString("prompt_select_persona", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Select a persona to apply to the chat.
        /// </summary>
        public static string prompt_selected_persona_hint {
            get {
                return ResourceManager.GetString("prompt_selected_persona_hint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на System prompt.
        /// </summary>
        public static string prompt_system_prompt {
            get {
                return ResourceManager.GetString("prompt_system_prompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Enter system prompt....
        /// </summary>
        public static string prompt_system_prompt_hint {
            get {
                return ResourceManager.GetString("prompt_system_prompt_hint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Text.
        /// </summary>
        public static string prompt_text {
            get {
                return ResourceManager.GetString("prompt_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Use custom persona.
        /// </summary>
        public static string prompt_use_custom_persona {
            get {
                return ResourceManager.GetString("prompt_use_custom_persona", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Application Hint.
        /// </summary>
        public static string promptcomponent_app_hint {
            get {
                return ResourceManager.GetString("promptcomponent-app_hint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Markdown Tips.
        /// </summary>
        public static string promptcomponent_markdown_tips {
            get {
                return ResourceManager.GetString("promptcomponent-markdown_tips", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Multiple Tools.
        /// </summary>
        public static string promptcomponent_multiple_tools {
            get {
                return ResourceManager.GetString("promptcomponent-multiple_tools", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Get Python installed packages.
        /// </summary>
        public static string python_get_installed_packages_list {
            get {
                return ResourceManager.GetString("python-get_installed_packages_list", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Python Venv activation script.
        /// </summary>
        public static string python_venv_activate_script_path_hint {
            get {
                return ResourceManager.GetString("python_venv_activate_script_path_hint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Reasoning process.
        /// </summary>
        public static string reasoning {
            get {
                return ResourceManager.GetString("reasoning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Regenerate.
        /// </summary>
        public static string regenerate {
            get {
                return ResourceManager.GetString("regenerate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Resend.
        /// </summary>
        public static string resend {
            get {
                return ResourceManager.GetString("resend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Reset.
        /// </summary>
        public static string reset {
            get {
                return ResourceManager.GetString("reset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Sample.
        /// </summary>
        public static string sample {
            get {
                return ResourceManager.GetString("sample", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Scripting.
        /// </summary>
        public static string scripting {
            get {
                return ResourceManager.GetString("scripting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Select model.
        /// </summary>
        public static string select_model {
            get {
                return ResourceManager.GetString("select_model", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Select Python Venv activation script.
        /// </summary>
        public static string select_python_venv_activate_script {
            get {
                return ResourceManager.GetString("select_python_venv_activate_script", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Select working directory.
        /// </summary>
        public static string select_working_directory {
            get {
                return ResourceManager.GetString("select_working_directory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Settings.
        /// </summary>
        public static string settings {
            get {
                return ResourceManager.GetString("settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Agentic model.
        /// </summary>
        public static string settings_agentic_model_hint {
            get {
                return ResourceManager.GetString("settings-agentic_model_hint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Chat model.
        /// </summary>
        public static string settings_chat_model_hint {
            get {
                return ResourceManager.GetString("settings-chat_model_hint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Default.
        /// </summary>
        public static string settings_default_id {
            get {
                return ResourceManager.GetString("settings_default_id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Profile:.
        /// </summary>
        public static string settings_profile {
            get {
                return ResourceManager.GetString("settings_profile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Summarization threshold (tokens).
        /// </summary>
        public static string settings_summarization_threshold {
            get {
                return ResourceManager.GetString("settings-summarization_threshold", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Summarizer model.
        /// </summary>
        public static string settings_summarizer_model_hint {
            get {
                return ResourceManager.GetString("settings-summarizer_model_hint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Enable MCP.
        /// </summary>
        public static string settings_use_mcp {
            get {
                return ResourceManager.GetString("settings-use_mcp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Enable tools.
        /// </summary>
        public static string settings_use_tools {
            get {
                return ResourceManager.GetString("settings-use_tools", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на System instructions.
        /// </summary>
        public static string system_instructions_hint {
            get {
                return ResourceManager.GetString("system_instructions_hint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Niggalink AI.
        /// </summary>
        public static string title {
            get {
                return ResourceManager.GetString("title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Tool arguments:.
        /// </summary>
        public static string tool_arguments {
            get {
                return ResourceManager.GetString("tool-arguments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на {0} tools.
        /// </summary>
        public static string tool_name_suffix_hint {
            get {
                return ResourceManager.GetString("tool_name_suffix_hint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Tool result:.
        /// </summary>
        public static string tool_result {
            get {
                return ResourceManager.GetString("tool-result", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на MCP.
        /// </summary>
        public static string tool_source_mcp {
            get {
                return ResourceManager.GetString("tool-source_mcp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Meta.
        /// </summary>
        public static string tool_source_meta {
            get {
                return ResourceManager.GetString("tool-source_meta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Tools.
        /// </summary>
        public static string tools_hint {
            get {
                return ResourceManager.GetString("tools_hint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Voice chat.
        /// </summary>
        public static string voice_chat {
            get {
                return ResourceManager.GetString("voice_chat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Web.
        /// </summary>
        public static string web {
            get {
                return ResourceManager.GetString("web", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Download.
        /// </summary>
        public static string web_download {
            get {
                return ResourceManager.GetString("web-download", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Fetch web content.
        /// </summary>
        public static string web_fetch {
            get {
                return ResourceManager.GetString("web-fetch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на GET request.
        /// </summary>
        public static string web_get {
            get {
                return ResourceManager.GetString("web-get", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Fetch HTML.
        /// </summary>
        public static string web_get_html {
            get {
                return ResourceManager.GetString("web-get_html", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Web parse.
        /// </summary>
        public static string web_parse {
            get {
                return ResourceManager.GetString("web-parse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на POST request.
        /// </summary>
        public static string web_post {
            get {
                return ResourceManager.GetString("web-post", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Web request.
        /// </summary>
        public static string web_request {
            get {
                return ResourceManager.GetString("web-request", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Web search.
        /// </summary>
        public static string web_search {
            get {
                return ResourceManager.GetString("web-search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Check web status.
        /// </summary>
        public static string web_status {
            get {
                return ResourceManager.GetString("web-status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Working directory.
        /// </summary>
        public static string working_directory_hint {
            get {
                return ResourceManager.GetString("working_directory_hint", resourceCulture);
            }
        }
    }
}
